site_name: Development Research in Practice
theme:
    name: material
    palette:
        primary: 'purple'
        accent: 'deep purple'
    logo:
        icon: _chrome_reader_mode_
    font:
        text: 'Nanum Gothic'
        code: 'Fira Mono'
